### ISSUE TITLE
PVWA Code 400 Bad requests responses to Safe-Management.ps1 execution via input from .csv

### ISSUE THREAD

**Issue by igrovirus** [cyberark/epv-api-scripts#234]
## Summary

Using the provided .CSV template files with the current version of Safe Management powershell script is unsuccessful.

## Steps to Reproduce

1. Executing:  
.\Safe-Management.ps1 -PVWAURL "https://cyberark-test.investcloud.int/PasswordVault" -Add -FilePath "C:\CyberArkInstall\epv-api-scripts-main\epv-api-scripts-main\Safe Management\safes-details-sample_2.csv"

2. Content of the safes-details-sample_2.csv (I've tried multiple files with various content just to make sure I'm not losing my mind, LDAP and CyberArk auth all giving similar errors):
Safename,Description,ManagingCPM,numVersionRetention,numDaysRetention,EnableOLAC
"TESTSAFE",This is the test safe,PasswordManager,,7,FALSE
"TEST_SAFE",This is a different test safe,PasswordManager,2,,FALSE
"TESTSAFE2",This is the test safe,PassManager2,,,

3. Example result:
PS C:\CyberArkInstall\epv-api-scripts-main\epv-api-scripts-main\Safe Management> .\Safe-Management.ps1 -PVWAURL "https://cyberark-test.investcloud.int/PasswordVault" -Add -FilePath "C:\CyberArkInstall\epv-api-scripts-main\epv-api-scripts-main\Safe Management\safes-details-sample_2.csv"
=======================================
Starting script (v2.0)
Importing safe TEST_SAFE with safe member ...
Safe TEST_SAFE does not exist
Adding the safe TEST_SAFE...
Error configuring safe 'TEST_SAFE'. Error: Source:; Message: New-Safe: Error adding TEST_SAFE to the Vault.
        ->Source:Microsoft.PowerShell.Commands.Utility; Message: The remote server returned an error: (400) Bad Request.
Importing safe TESTSAFE with safe member ...
Safe TESTSAFE does not exist
Adding the safe TESTSAFE...
Error configuring safe 'TESTSAFE'. Error: Source:; Message: New-Safe: Error adding TESTSAFE to the Vault.
        ->Source:Microsoft.PowerShell.Commands.Utility; Message: The remote server returned an error: (400) Bad Request.
Importing safe TESTSAFE2 with safe member ...
Safe TESTSAFE2 exists
Safe TESTSAFE2 already exists, to update it use the Update switch
Logoff Session...
Script ended
=======================================

PS C:\CyberArkInstall\epv-api-scripts-main\epv-api-scripts-main\Safe Management> .\Safe-Management.ps1 -PVWAURL "https://cyberark-test.investcloud.int/PasswordVault" -Add -FilePath "C:\CyberArkInstall\epv-api-scripts-main\epv-api-scripts-main\Safe Management\safes-details-sample_2.csv" -AuthType LDAP
=======================================
Starting script (v2.0)
Importing safe TEST_SAFE13 with safe member ...
Safe TEST_SAFE13 does not exist
Adding the safe TEST_SAFE13...
Error configuring safe 'TEST_SAFE13'. Error: Source:; Message: New-Safe: Error adding TEST_SAFE13 to the Vault.
        ->Source:Microsoft.PowerShell.Commands.Utility; Message: The remote server returned an error: (400) Bad Request.
Importing safe TESTSAFE12 with safe member ...
Safe TESTSAFE12 does not exist
Adding the safe TESTSAFE12...
Error configuring safe 'TESTSAFE12'. Error: Source:; Message: New-Safe: Error adding TESTSAFE12 to the Vault.
        ->Source:Microsoft.PowerShell.Commands.Utility; Message: The remote server returned an error: (400) Bad Request.
Importing safe TESTSAFE14 with safe member ...
Safe TESTSAFE14 does not exist
Adding the safe TESTSAFE14...
Error configuring safe 'TESTSAFE14'. Error: Source:; Message: New-Safe: Error adding TESTSAFE14 to the Vault.
        ->Source:Microsoft.PowerShell.Commands.Utility; Message: The remote server returned an error: (400) Bad Request.
Logoff Session...
Script ended
=======================================

4. PVWA shows:
2022-02-24 22:59:33,795 DEBUG [24]   c168dae9-14e0-4401-a98e-e0b4c294c6a1 Casos Session Request[GetSessionToken] ended.  [Casos]
2022-02-24 22:59:33,795 DEBUG [24]   c168dae9-14e0-4401-a98e-e0b4c294c6a1 CyberArk.PasswordVault.WebServices.Infra.Exceptions.ValidationParametersException: PASWS167E There are some invalid parameters
   at CyberArk.PasswordVault.WebServices.Infra.Filters.ValidationActionFilter.OnActionExecuting(HttpActionContext actionContext)
   at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutingAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()  []
2022-02-24 22:59:33,810 DEBUG [24]   c168dae9-14e0-4401-a98e-e0b4c294c6a1 AddSafe failed CyberArk.PasswordVault.WebServices.Infra.Exceptions.ValidationParametersException: PASWS167E There are some invalid parameters
   at CyberArk.PasswordVault.WebServices.Infra.Filters.ValidationActionFilter.OnActionExecuting(HttpActionContext actionContext)
   at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutingAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() [SafesController]
2022-02-24 22:59:33,810 WARN  [24]   c168dae9-14e0-4401-a98e-e0b4c294c6a1 AddSafe Response:: Code: 400. Content: {"Details":[{"ErrorCode":"PASWS011E","ErrorMessage":"Missing mandatory parameter [SafeName].","ParameterName":"SafeName"}],"ErrorCode":"PASWS167E","ErrorMessage":"There are some invalid parameters"}  [SafesController]
2022-02-24 22:59:33,810 INFO  [24]   c168dae9-14e0-4401-a98e-e0b4c294c6a1 EndRequest /PasswordVault/api/Safes | code: 400  [up]

## Expected Results

Expected to create new safes using safes-details-sample.csv file or similar files.

## Actual Results

Receive a 400 Bad Request error from PVWA, further details specific Invalid Parameters and Missing mandatory parameter [SafeName] 

## Reproducible

   * [X] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
epv-api-scripts was downloaded on ~2:30PM EST 02/24/2022. Using Powershell:
Name                           Value
----                           -----
PSVersion                      5.1.17763.2268
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.2268
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

CyberArk PVWA:
Version 12.2.2 (12.2.2.56)

*What version of the product are you running? Any version info that you can
share is helpful.  For example, you might give the version from Docker logs,
the Docker tag, a specific download URL, the output of the `/info` route, etc.*

## Environment setup
PVWA Has internal CA cert, recognized by the CPM where it's executed, running in Admin powershell window. Network connectivity is successfull, and can execute commands directly with flags i.e. -List or -Add *flags*. Cannot create/update in bulk specifically through CSV.

* Can you describe the environment in which this product is running? Is it running on a VM / in a container / in a cloud? 
* Which cloud provider? Which container orchestrator (including version)? 
* The more info you can share about your runtime environment, the better we may be able to reproduce the issue.

## Additional Information

*Add any other context about the problem here.*

**Comment by psingh308** [comment]
Hi @AssafMiron , I'm facing the same issue while using the safe management script. PVWA version is 11.6. Is it script do not support for v11.6?

**Comment by AssafMiron** [comment]
@bab29

**Comment by bab29** [comment]
No response received

**Comment by cybr-jh** [comment]
My customer is reporting similar error when running this script against Privilege Cloud PVWA 12.5.
